// Complete list of countries with dial codes and flag emojis
// Sorted: Italia first, then alphabetical by Italian name

export interface PhoneCountry {
  code: string;    // ISO 3166-1 alpha-2
  name: string;    // Italian name
  dial: string;    // Dial code with +
  flag: string;    // Flag emoji
}

export const PHONE_COUNTRIES: PhoneCountry[] = [
  { code: 'IT', name: 'Italia', dial: '+39', flag: '🇮🇹' },
  { code: 'AF', name: 'Afghanistan', dial: '+93', flag: '🇦🇫' },
  { code: 'AL', name: 'Albania', dial: '+355', flag: '🇦🇱' },
  { code: 'DZ', name: 'Algeria', dial: '+213', flag: '🇩🇿' },
  { code: 'AD', name: 'Andorra', dial: '+376', flag: '🇦🇩' },
  { code: 'AO', name: 'Angola', dial: '+244', flag: '🇦🇴' },
  { code: 'AG', name: 'Antigua e Barbuda', dial: '+1-268', flag: '🇦🇬' },
  { code: 'SA', name: 'Arabia Saudita', dial: '+966', flag: '🇸🇦' },
  { code: 'AR', name: 'Argentina', dial: '+54', flag: '🇦🇷' },
  { code: 'AM', name: 'Armenia', dial: '+374', flag: '🇦🇲' },
  { code: 'AU', name: 'Australia', dial: '+61', flag: '🇦🇺' },
  { code: 'AT', name: 'Austria', dial: '+43', flag: '🇦🇹' },
  { code: 'AZ', name: 'Azerbaigian', dial: '+994', flag: '🇦🇿' },
  { code: 'BS', name: 'Bahamas', dial: '+1-242', flag: '🇧🇸' },
  { code: 'BH', name: 'Bahrein', dial: '+973', flag: '🇧🇭' },
  { code: 'BD', name: 'Bangladesh', dial: '+880', flag: '🇧🇩' },
  { code: 'BB', name: 'Barbados', dial: '+1-246', flag: '🇧🇧' },
  { code: 'BE', name: 'Belgio', dial: '+32', flag: '🇧🇪' },
  { code: 'BZ', name: 'Belize', dial: '+501', flag: '🇧🇿' },
  { code: 'BJ', name: 'Benin', dial: '+229', flag: '🇧🇯' },
  { code: 'BT', name: 'Bhutan', dial: '+975', flag: '🇧🇹' },
  { code: 'BY', name: 'Bielorussia', dial: '+375', flag: '🇧🇾' },
  { code: 'MM', name: 'Birmania', dial: '+95', flag: '🇲🇲' },
  { code: 'BO', name: 'Bolivia', dial: '+591', flag: '🇧🇴' },
  { code: 'BA', name: 'Bosnia ed Erzegovina', dial: '+387', flag: '🇧🇦' },
  { code: 'BW', name: 'Botswana', dial: '+267', flag: '🇧🇼' },
  { code: 'BR', name: 'Brasile', dial: '+55', flag: '🇧🇷' },
  { code: 'BN', name: 'Brunei', dial: '+673', flag: '🇧🇳' },
  { code: 'BG', name: 'Bulgaria', dial: '+359', flag: '🇧🇬' },
  { code: 'BF', name: 'Burkina Faso', dial: '+226', flag: '🇧🇫' },
  { code: 'BI', name: 'Burundi', dial: '+257', flag: '🇧🇮' },
  { code: 'KH', name: 'Cambogia', dial: '+855', flag: '🇰🇭' },
  { code: 'CM', name: 'Camerun', dial: '+237', flag: '🇨🇲' },
  { code: 'CA', name: 'Canada', dial: '+1', flag: '🇨🇦' },
  { code: 'CV', name: 'Capo Verde', dial: '+238', flag: '🇨🇻' },
  { code: 'TD', name: 'Ciad', dial: '+235', flag: '🇹🇩' },
  { code: 'CL', name: 'Cile', dial: '+56', flag: '🇨🇱' },
  { code: 'CN', name: 'Cina', dial: '+86', flag: '🇨🇳' },
  { code: 'CY', name: 'Cipro', dial: '+357', flag: '🇨🇾' },
  { code: 'CO', name: 'Colombia', dial: '+57', flag: '🇨🇴' },
  { code: 'KM', name: 'Comore', dial: '+269', flag: '🇰🇲' },
  { code: 'KP', name: 'Corea del Nord', dial: '+850', flag: '🇰🇵' },
  { code: 'KR', name: 'Corea del Sud', dial: '+82', flag: '🇰🇷' },
  { code: 'CI', name: "Costa d'Avorio", dial: '+225', flag: '🇨🇮' },
  { code: 'CR', name: 'Costa Rica', dial: '+506', flag: '🇨🇷' },
  { code: 'HR', name: 'Croazia', dial: '+385', flag: '🇭🇷' },
  { code: 'CU', name: 'Cuba', dial: '+53', flag: '🇨🇺' },
  { code: 'DK', name: 'Danimarca', dial: '+45', flag: '🇩🇰' },
  { code: 'DM', name: 'Dominica', dial: '+1-767', flag: '🇩🇲' },
  { code: 'EC', name: 'Ecuador', dial: '+593', flag: '🇪🇨' },
  { code: 'EG', name: 'Egitto', dial: '+20', flag: '🇪🇬' },
  { code: 'SV', name: 'El Salvador', dial: '+503', flag: '🇸🇻' },
  { code: 'AE', name: 'Emirati Arabi Uniti', dial: '+971', flag: '🇦🇪' },
  { code: 'ER', name: 'Eritrea', dial: '+291', flag: '🇪🇷' },
  { code: 'EE', name: 'Estonia', dial: '+372', flag: '🇪🇪' },
  { code: 'SZ', name: 'Eswatini', dial: '+268', flag: '🇸🇿' },
  { code: 'ET', name: 'Etiopia', dial: '+251', flag: '🇪🇹' },
  { code: 'FJ', name: 'Figi', dial: '+679', flag: '🇫🇯' },
  { code: 'PH', name: 'Filippine', dial: '+63', flag: '🇵🇭' },
  { code: 'FI', name: 'Finlandia', dial: '+358', flag: '🇫🇮' },
  { code: 'FR', name: 'Francia', dial: '+33', flag: '🇫🇷' },
  { code: 'GA', name: 'Gabon', dial: '+241', flag: '🇬🇦' },
  { code: 'GM', name: 'Gambia', dial: '+220', flag: '🇬🇲' },
  { code: 'GE', name: 'Georgia', dial: '+995', flag: '🇬🇪' },
  { code: 'DE', name: 'Germania', dial: '+49', flag: '🇩🇪' },
  { code: 'GH', name: 'Ghana', dial: '+233', flag: '🇬🇭' },
  { code: 'JM', name: 'Giamaica', dial: '+1-876', flag: '🇯🇲' },
  { code: 'JP', name: 'Giappone', dial: '+81', flag: '🇯🇵' },
  { code: 'DJ', name: 'Gibuti', dial: '+253', flag: '🇩🇯' },
  { code: 'JO', name: 'Giordania', dial: '+962', flag: '🇯🇴' },
  { code: 'GR', name: 'Grecia', dial: '+30', flag: '🇬🇷' },
  { code: 'GD', name: 'Grenada', dial: '+1-473', flag: '🇬🇩' },
  { code: 'GT', name: 'Guatemala', dial: '+502', flag: '🇬🇹' },
  { code: 'GN', name: 'Guinea', dial: '+224', flag: '🇬🇳' },
  { code: 'GQ', name: 'Guinea Equatoriale', dial: '+240', flag: '🇬🇶' },
  { code: 'GW', name: 'Guinea-Bissau', dial: '+245', flag: '🇬🇼' },
  { code: 'GY', name: 'Guyana', dial: '+592', flag: '🇬🇾' },
  { code: 'HT', name: 'Haiti', dial: '+509', flag: '🇭🇹' },
  { code: 'HN', name: 'Honduras', dial: '+504', flag: '🇭🇳' },
  { code: 'IN', name: 'India', dial: '+91', flag: '🇮🇳' },
  { code: 'ID', name: 'Indonesia', dial: '+62', flag: '🇮🇩' },
  { code: 'IR', name: 'Iran', dial: '+98', flag: '🇮🇷' },
  { code: 'IQ', name: 'Iraq', dial: '+964', flag: '🇮🇶' },
  { code: 'IE', name: 'Irlanda', dial: '+353', flag: '🇮🇪' },
  { code: 'IS', name: 'Islanda', dial: '+354', flag: '🇮🇸' },
  { code: 'MH', name: 'Isole Marshall', dial: '+692', flag: '🇲🇭' },
  { code: 'SB', name: 'Isole Salomone', dial: '+677', flag: '🇸🇧' },
  { code: 'IL', name: 'Israele', dial: '+972', flag: '🇮🇱' },
  { code: 'KZ', name: 'Kazakistan', dial: '+7', flag: '🇰🇿' },
  { code: 'KE', name: 'Kenya', dial: '+254', flag: '🇰🇪' },
  { code: 'KG', name: 'Kirghizistan', dial: '+996', flag: '🇰🇬' },
  { code: 'KI', name: 'Kiribati', dial: '+686', flag: '🇰🇮' },
  { code: 'KW', name: 'Kuwait', dial: '+965', flag: '🇰🇼' },
  { code: 'LA', name: 'Laos', dial: '+856', flag: '🇱🇦' },
  { code: 'LS', name: 'Lesotho', dial: '+266', flag: '🇱🇸' },
  { code: 'LV', name: 'Lettonia', dial: '+371', flag: '🇱🇻' },
  { code: 'LB', name: 'Libano', dial: '+961', flag: '🇱🇧' },
  { code: 'LR', name: 'Liberia', dial: '+231', flag: '🇱🇷' },
  { code: 'LY', name: 'Libia', dial: '+218', flag: '🇱🇾' },
  { code: 'LI', name: 'Liechtenstein', dial: '+423', flag: '🇱🇮' },
  { code: 'LT', name: 'Lituania', dial: '+370', flag: '🇱🇹' },
  { code: 'LU', name: 'Lussemburgo', dial: '+352', flag: '🇱🇺' },
  { code: 'MK', name: 'Macedonia del Nord', dial: '+389', flag: '🇲🇰' },
  { code: 'MG', name: 'Madagascar', dial: '+261', flag: '🇲🇬' },
  { code: 'MW', name: 'Malawi', dial: '+265', flag: '🇲🇼' },
  { code: 'MY', name: 'Malesia', dial: '+60', flag: '🇲🇾' },
  { code: 'MV', name: 'Maldive', dial: '+960', flag: '🇲🇻' },
  { code: 'ML', name: 'Mali', dial: '+223', flag: '🇲🇱' },
  { code: 'MT', name: 'Malta', dial: '+356', flag: '🇲🇹' },
  { code: 'MA', name: 'Marocco', dial: '+212', flag: '🇲🇦' },
  { code: 'MR', name: 'Mauritania', dial: '+222', flag: '🇲🇷' },
  { code: 'MU', name: 'Mauritius', dial: '+230', flag: '🇲🇺' },
  { code: 'MX', name: 'Messico', dial: '+52', flag: '🇲🇽' },
  { code: 'FM', name: 'Micronesia', dial: '+691', flag: '🇫🇲' },
  { code: 'MD', name: 'Moldavia', dial: '+373', flag: '🇲🇩' },
  { code: 'MC', name: 'Monaco', dial: '+377', flag: '🇲🇨' },
  { code: 'MN', name: 'Mongolia', dial: '+976', flag: '🇲🇳' },
  { code: 'ME', name: 'Montenegro', dial: '+382', flag: '🇲🇪' },
  { code: 'MZ', name: 'Mozambico', dial: '+258', flag: '🇲🇿' },
  { code: 'NA', name: 'Namibia', dial: '+264', flag: '🇳🇦' },
  { code: 'NR', name: 'Nauru', dial: '+674', flag: '🇳🇷' },
  { code: 'NP', name: 'Nepal', dial: '+977', flag: '🇳🇵' },
  { code: 'NI', name: 'Nicaragua', dial: '+505', flag: '🇳🇮' },
  { code: 'NE', name: 'Niger', dial: '+227', flag: '🇳🇪' },
  { code: 'NG', name: 'Nigeria', dial: '+234', flag: '🇳🇬' },
  { code: 'NO', name: 'Norvegia', dial: '+47', flag: '🇳🇴' },
  { code: 'NZ', name: 'Nuova Zelanda', dial: '+64', flag: '🇳🇿' },
  { code: 'OM', name: 'Oman', dial: '+968', flag: '🇴🇲' },
  { code: 'NL', name: 'Paesi Bassi', dial: '+31', flag: '🇳🇱' },
  { code: 'PK', name: 'Pakistan', dial: '+92', flag: '🇵🇰' },
  { code: 'PW', name: 'Palau', dial: '+680', flag: '🇵🇼' },
  { code: 'PA', name: 'Panama', dial: '+507', flag: '🇵🇦' },
  { code: 'PG', name: 'Papua Nuova Guinea', dial: '+675', flag: '🇵🇬' },
  { code: 'PY', name: 'Paraguay', dial: '+595', flag: '🇵🇾' },
  { code: 'PE', name: 'Peru', dial: '+51', flag: '🇵🇪' },
  { code: 'PL', name: 'Polonia', dial: '+48', flag: '🇵🇱' },
  { code: 'PT', name: 'Portogallo', dial: '+351', flag: '🇵🇹' },
  { code: 'QA', name: 'Qatar', dial: '+974', flag: '🇶🇦' },
  { code: 'GB', name: 'Regno Unito', dial: '+44', flag: '🇬🇧' },
  { code: 'CZ', name: 'Repubblica Ceca', dial: '+420', flag: '🇨🇿' },
  { code: 'CF', name: 'Repubblica Centrafricana', dial: '+236', flag: '🇨🇫' },
  { code: 'CG', name: 'Repubblica del Congo', dial: '+242', flag: '🇨🇬' },
  { code: 'CD', name: 'Repubblica Democratica del Congo', dial: '+243', flag: '🇨🇩' },
  { code: 'DO', name: 'Repubblica Dominicana', dial: '+1-809', flag: '🇩🇴' },
  { code: 'RO', name: 'Romania', dial: '+40', flag: '🇷🇴' },
  { code: 'RW', name: 'Ruanda', dial: '+250', flag: '🇷🇼' },
  { code: 'RU', name: 'Russia', dial: '+7', flag: '🇷🇺' },
  { code: 'KN', name: 'Saint Kitts e Nevis', dial: '+1-869', flag: '🇰🇳' },
  { code: 'VC', name: 'Saint Vincent e Grenadine', dial: '+1-784', flag: '🇻🇨' },
  { code: 'LC', name: 'Santa Lucia', dial: '+1-758', flag: '🇱🇨' },
  { code: 'WS', name: 'Samoa', dial: '+685', flag: '🇼🇸' },
  { code: 'SM', name: 'San Marino', dial: '+378', flag: '🇸🇲' },
  { code: 'ST', name: 'Sao Tome e Principe', dial: '+239', flag: '🇸🇹' },
  { code: 'SN', name: 'Senegal', dial: '+221', flag: '🇸🇳' },
  { code: 'RS', name: 'Serbia', dial: '+381', flag: '🇷🇸' },
  { code: 'SC', name: 'Seychelles', dial: '+248', flag: '🇸🇨' },
  { code: 'SL', name: 'Sierra Leone', dial: '+232', flag: '🇸🇱' },
  { code: 'SG', name: 'Singapore', dial: '+65', flag: '🇸🇬' },
  { code: 'SY', name: 'Siria', dial: '+963', flag: '🇸🇾' },
  { code: 'SK', name: 'Slovacchia', dial: '+421', flag: '🇸🇰' },
  { code: 'SI', name: 'Slovenia', dial: '+386', flag: '🇸🇮' },
  { code: 'SO', name: 'Somalia', dial: '+252', flag: '🇸🇴' },
  { code: 'ES', name: 'Spagna', dial: '+34', flag: '🇪🇸' },
  { code: 'LK', name: 'Sri Lanka', dial: '+94', flag: '🇱🇰' },
  { code: 'US', name: 'Stati Uniti', dial: '+1', flag: '🇺🇸' },
  { code: 'ZA', name: 'Sudafrica', dial: '+27', flag: '🇿🇦' },
  { code: 'SD', name: 'Sudan', dial: '+249', flag: '🇸🇩' },
  { code: 'SS', name: 'Sudan del Sud', dial: '+211', flag: '🇸🇸' },
  { code: 'SR', name: 'Suriname', dial: '+597', flag: '🇸🇷' },
  { code: 'SE', name: 'Svezia', dial: '+46', flag: '🇸🇪' },
  { code: 'CH', name: 'Svizzera', dial: '+41', flag: '🇨🇭' },
  { code: 'TJ', name: 'Tagikistan', dial: '+992', flag: '🇹🇯' },
  { code: 'TW', name: 'Taiwan', dial: '+886', flag: '🇹🇼' },
  { code: 'TZ', name: 'Tanzania', dial: '+255', flag: '🇹🇿' },
  { code: 'TH', name: 'Thailandia', dial: '+66', flag: '🇹🇭' },
  { code: 'TL', name: 'Timor Est', dial: '+670', flag: '🇹🇱' },
  { code: 'TG', name: 'Togo', dial: '+228', flag: '🇹🇬' },
  { code: 'TO', name: 'Tonga', dial: '+676', flag: '🇹🇴' },
  { code: 'TT', name: 'Trinidad e Tobago', dial: '+1-868', flag: '🇹🇹' },
  { code: 'TN', name: 'Tunisia', dial: '+216', flag: '🇹🇳' },
  { code: 'TR', name: 'Turchia', dial: '+90', flag: '🇹🇷' },
  { code: 'TM', name: 'Turkmenistan', dial: '+993', flag: '🇹🇲' },
  { code: 'TV', name: 'Tuvalu', dial: '+688', flag: '🇹🇻' },
  { code: 'UA', name: 'Ucraina', dial: '+380', flag: '🇺🇦' },
  { code: 'UG', name: 'Uganda', dial: '+256', flag: '🇺🇬' },
  { code: 'HU', name: 'Ungheria', dial: '+36', flag: '🇭🇺' },
  { code: 'UY', name: 'Uruguay', dial: '+598', flag: '🇺🇾' },
  { code: 'UZ', name: 'Uzbekistan', dial: '+998', flag: '🇺🇿' },
  { code: 'VU', name: 'Vanuatu', dial: '+678', flag: '🇻🇺' },
  { code: 'VA', name: 'Vaticano', dial: '+39', flag: '🇻🇦' },
  { code: 'VE', name: 'Venezuela', dial: '+58', flag: '🇻🇪' },
  { code: 'VN', name: 'Vietnam', dial: '+84', flag: '🇻🇳' },
  { code: 'YE', name: 'Yemen', dial: '+967', flag: '🇾🇪' },
  { code: 'ZM', name: 'Zambia', dial: '+260', flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabwe', dial: '+263', flag: '🇿🇼' },
];

export function findCountryByDial(dial: string): PhoneCountry | undefined {
  return PHONE_COUNTRIES.find(c => c.dial === dial);
}

export function findCountryByCode(code: string): PhoneCountry | undefined {
  return PHONE_COUNTRIES.find(c => c.code === code);
}

export function findCountryByName(name: string): PhoneCountry | undefined {
  return PHONE_COUNTRIES.find(c => c.name.toLowerCase() === name.toLowerCase());
}
