-- Add Nexi payment fields to bookings table
-- Migration: add_nexi_payment_fields

-- Add new columns for Nexi payments
ALTER TABLE bookings 
  ADD COLUMN IF NOT EXISTS nexi_order_id VARCHAR(255),
  ADD COLUMN IF NOT EXISTS nexi_payment_id VARCHAR(255),
  ADD COLUMN IF NOT EXISTS nexi_transaction_date TIMESTAMP,
  ADD COLUMN IF NOT EXISTS payment_provider VARCHAR(50) DEFAULT 'nexi',
  ADD COLUMN IF NOT EXISTS payment_error TEXT;

-- Add indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_bookings_nexi_order_id 
  ON bookings(nexi_order_id);

CREATE INDEX IF NOT EXISTS idx_bookings_nexi_payment_id 
  ON bookings(nexi_payment_id);

CREATE INDEX IF NOT EXISTS idx_bookings_payment_provider 
  ON bookings(payment_provider);

-- Update existing Stripe records to mark them as Stripe
UPDATE bookings 
SET payment_provider = 'stripe' 
WHERE stripe_payment_intent_id IS NOT NULL 
  AND payment_provider IS NULL;

-- Add comment to document the fields
COMMENT ON COLUMN bookings.nexi_order_id IS 'Nexi order ID (codTrans) generated by our system';
COMMENT ON COLUMN bookings.nexi_payment_id IS 'Nexi payment authorization code (codAut) from successful payment';
COMMENT ON COLUMN bookings.nexi_transaction_date IS 'Date and time of Nexi transaction';
COMMENT ON COLUMN bookings.payment_provider IS 'Payment provider used: stripe, nexi, or credit_wallet';
COMMENT ON COLUMN bookings.payment_error IS 'Error message if payment failed';
